CREATE DATABASE Judson_Santana_Atividade01;

USE Judson_Santana_Atividade01;

CREATE TABLE PERFIL

(
	ID				INT				NOT NULL IDENTITY(1,1),
	NOME			VARCHAR(50)		NOT	NULL,
	DESCRICAO		VARCHAR(500)	NULL,
	CONSTRAINT PK_PERFIL PRIMARY KEY(ID)
);

CREATE TABLE ACESSO

(
	ID					INT				NOT NULL IDENTITY(1,1),
	ID_PERFIL			INT				NOT	NULL,
	NOME				VARCHAR(50)		NOT NULL,
	LOGIN				VARCHAR(50)		NOT NULL,
	EMAIL				VARCHAR(100)	NOT NULL,
	SENHA				VARCHAR(100)	NOT NULL,
	ULTIMO_ACESSO		DATETIME		NULL,
	CONSTRAINT	PK_ACESSO PRIMARY KEY(ID),
	CONSTRAINT	FK_ACESSO_PERFIL FOREIGN KEY (ID_PERFIL)
	REFERENCES PERFIL (ID)
);

CREATE TABLE CLIENTE

(
	ID					INT				NOT NULL IDENTITY(1,1),
	NOME				VARCHAR(50)		NOT NULL,
	SOBRENOME			VARCHAR(100)	NULL,
	DT_NASC				DATE			NULL,
	NATURALIDADE		VARCHAR(100)	NULL,
	NOME_MAE			VARCHAR(50)		NULL,
	NOME_PAI			VARCHAR(50)		NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
);

CREATE TABLE EMAIL_CLIENTE

(
	ID					INT				NOT NULL IDENTITY(1,1),
	ID_CLIENTE			INT				NOT NULL,
	EMAIL				VARCHAR(100)	NOT NULL,
	CONSTRAINT PK_EMAIL_CLIENTE PRIMARY KEY (ID),
	CONSTRAINT FK_EMAIL_CLIENTE_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (ID)
);

CREATE TABLE TIPO_TELEFONE_CLIENTE

(
	ID					INT				NOT NULL IDENTITY(1,1),
	NOME				VARCHAR(50)		NOT NULL,
	DESCRICAO			VARCHAR(500)	NULL,
	CONSTRAINT PK_TIPO_TELEFONE_CLIENTE PRIMARY KEY (ID)
);

CREATE TABLE TELEFONE_CLIENTE

(
	ID							INT				NOT NULL IDENTITY(1,1),
	ID_CLIENTE					INT				NOT NULL,
	ID_TIPO_TELEFONE_CLIENTE	INT				NOT NULL,
	DDD							VARCHAR(3)		NOT NULL,
	N_TELEFONE					VARCHAR(9)		NOT NULL,
	CONSTRAINT PK_TELEFONE_CLIENTE PRIMARY KEY (ID),
	CONSTRAINT FK_TELEFONE_CLIENTE_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (ID),
	CONSTRAINT FK_TELEFONE_CLIENTE_TIPO_TELEFONE_CLIENTE FOREIGN KEY (ID_TIPO_TELEFONE_CLIENTE)
	REFERENCES TIPO_TELEFONE_CLIENTE (ID)
);

CREATE TABLE TIPO_ENDERECO_CLIENTE

(
	ID				INT				NOT NULL IDENTITY(1,1),
	NOME			VARCHAR(50)		NOT NULL,
	DESCRICAO		VARCHAR(500)	NULL,
	CONSTRAINT PK_TIPO_ENDERECO_CLIENTE PRIMARY KEY (ID)
);

CREATE TABLE PAIS_CLIENTE

(
	ID				INT				NOT NULL IDENTITY(1,1),
	NOME			VARCHAR(50)		NOT NULL,
	DESCRICAO		VARCHAR(500)	NOT NULL,
	CONSTRAINT PK_PAIS_CLIENTE PRIMARY KEY (ID)
);

CREATE TABLE UF_CLIENTE

(
	ID					INT				NOT NULL IDENTITY(1,1),
	ID_PAIS_CLIENTE		INT				NOT NULL,
	NOME				VARCHAR(50)		NOT NULL,
	SIGLA				VARCHAR(3)		NOT NULL,
	CONSTRAINT PK_UF_CLIENTE PRIMARY KEY (ID),
	CONSTRAINT FK_UF_CLIENTE_PAIS_CLIENTE FOREIGN KEY (ID_PAIS_CLIENTE)
	REFERENCES PAIS_CLIENTE (ID)
);

CREATE TABLE CIDADE_CLIENTE

(
	ID					INT				NOT NULL IDENTITY(1,1),
	ID_UF_CLIENTE		INT				NOT NULL,
	NOME				VARCHAR(50)		NOT NULL,
	CONSTRAINT PK_CIDADE_CLIENTE PRIMARY KEY (ID),
	CONSTRAINT FK_CIDADE_CLIENTE_UF_CLIENTE FOREIGN KEY (ID_UF_CLIENTE)
	REFERENCES UF_CLIENTE(ID)
);

CREATE TABLE ENDERECO_CLIENTE

(
	ID							INT				NOT NULL IDENTITY(1,1),
	ID_CLIENTE					INT				NOT NULL,
	ID_TIPO_ENDERECO_CLIENTE	INT				NOT NULL,
	ID_CIDADE_CLIENTE			INT				NOT NULL,
	TIPO_LOGRADOURO				VARCHAR(20)		NOT NULL,
	NOME_LOGRADOURO				VARCHAR(100)	NOT NULL,
	NUMERO						VARCHAR(6)		NULL,
	COMPLEMENTO					VARCHAR(20)		NULL,
	BAIRRO						VARCHAR(50)		NOT NULL,
	CEP							VARCHAR(10)		NULL,
	CONSTRAINT PK_ENDERECO_CLIENTE PRIMARY KEY (ID),
	CONSTRAINT FK_ENDERECO_CLIENTE_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (ID),
	CONSTRAINT FK_ENDERECO_CLIENTE_TIPO_ENDERECO_CLIENTE FOREIGN KEY (ID_TIPO_ENDERECO_CLIENTE)
	REFERENCES TIPO_ENDERECO_CLIENTE (ID),
	CONSTRAINT FK_ENDERECO_CLIENTE_CIDADE_CLIENTE FOREIGN KEY (ID_CIDADE_CLIENTE)
	REFERENCES CIDADE_CLIENTE (ID)
);

CREATE TABLE TIPO_DOCUMENTO_CLIENTE

(
	ID			INT				NOT NULL IDENTITY(1,1),
	NOME		VARCHAR(50)		NOT NULL,
	DESCRICAO	VARCHAR(500)	NULL,
	CONSTRAINT PK_TIPO_DOCUMENTO_CLIENTE PRIMARY KEY (ID)
);

CREATE TABLE DOCUMENTO_CLIENTE

(
	ID								INT				NOT NULL IDENTITY(1,1),
	ID_CLIENTE						INT				NOT NULL,
	ID_TIPO_DOCUMENTO_CLIENTE		INT				NOT NULL,
	N_DOCUMENTO						VARCHAR(50)		NOT NULL,
	CONSTRAINT PK_DOCUMENTO_CLIENTE PRIMARY KEY (ID),
	CONSTRAINT FK_DOCUMENTO_CLIENTE_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (ID),
	CONSTRAINT FK_DOCUMENTO_CLIENTE_TIPO_DOCUMENTO_CLIENTE FOREIGN KEY (ID_TIPO_DOCUMENTO_CLIENTE)
	REFERENCES TIPO_DOCUMENTO_CLIENTE (ID)
);

CREATE TABLE FORNECEDOR

(
	ID				INT				NOT NULL IDENTITY(1,1),
	RAZAO_SOCIAL	VARCHAR(100)	NOT NULL,
	NOME_FANTASIA	VARCHAR(50)		NULL,
	CNPJ			VARCHAR(20)		NOT NULL,
	DT_CADASTRO		DATE			NULL,
	CONSTRAINT PK_FORNECEDOR PRIMARY KEY (ID)
);

CREATE TABLE ENDERECO_FORNECEDOR

(
	ID_FORNECEDOR		INT				NOT NULL,
	TIPO_LOGRADOURO		VARCHAR(20)		NOT NULL,
	NOME_LOGRADOURO		VARCHAR(50)		NOT NULL,
	NUMERO				VARCHAR(6)		NULL,
	COMPLEMENTO			VARCHAR(20)		NULL,
	BAIRRO				VARCHAR(50)		NOT NULL,
	CIDADE				VARCHAR(50)		NOT NULL,
	CEP					VARCHAR(8)		NULL,
	UF					VARCHAR(3)		NOT NULL,
	PAIS				VARCHAR(20)		NOT NULL,
	CONSTRAINT PK_ENDERECO_FORNECEDOR PRIMARY KEY (ID_FORNECEDOR),
	CONSTRAINT FK_ENDERECO_FORNECEDOR_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR)
	REFERENCES FORNECEDOR (ID)
);

CREATE TABLE CONTATOS_FORNECEDOR

(
	ID				INT				NOT NULL IDENTITY(1,1),
	ID_FORNECEDOR	INT				NOT NULL,
	NOME			VARCHAR(50)		NOT NULL,
	EMAIL			VARCHAR(100)	NOT NULL
	CONSTRAINT PK_CONTATOS_FORNECEDOR PRIMARY KEY (ID)
	CONSTRAINT FK_CONTATOS_FORNECEDOR_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR)
	REFERENCES FORNECEDOR (ID)
);

CREATE TABLE TIPO_TELEFONE_CONTATOS_FORNECEDOR

(
	ID					INT				NOT NULL IDENTITY(1,1),
	NOME				VARCHAR(50)		NOT NULL,
	DESCRICAO			VARCHAR(500)	NULL,
	CONSTRAINT PK_TIPO_TELEFONE_CONTATOS_FORNECEDOR PRIMARY KEY (ID)
);

CREATE TABLE TELEFONE_CONTATOS_FORNECEDOR

(
	ID										INT				NOT NULL IDENTITY(1,1),
	ID_CONTATOS_FORNECEDOR					INT				NOT NULL,
	ID_TIPO_TELEFONE_CONTATOS_FORNECEDOR	INT				NOT NULL,
	DDD										VARCHAR(3)		NOT NULL,
	N_TELEFONE								VARCHAR(9)		NOT NULL,
	CONSTRAINT PK_TELEFONE_CONTATOS_FORNECEDOR PRIMARY KEY (ID),
	CONSTRAINT FK_TELEFONE_CONTATOS_FORNECEDOR_CONTATOS_FORNECEDOR FOREIGN KEY (ID_CONTATOS_FORNECEDOR)
	REFERENCES CONTATOS_FORNECEDOR (ID),
	CONSTRAINT FK_TELEFONE_CONTATOS_FORNECEDOR_TIPO_TELEFONE_CONTATOS_FORNECEDOR FOREIGN KEY (ID_TIPO_TELEFONE_CONTATOS_FORNECEDOR)
	REFERENCES TIPO_TELEFONE_CONTATOS_FORNECEDOR (ID)
);

CREATE TABLE CARGO_SETOR_CONTATOS_FORNECEDOR

(
	ID_CONTATOS_FORNECEDOR		INT				NOT NULL,
	NOME_CARGO					VARCHAR(50)		NOT NULL,
	NOME_SETOR					VARCHAR(50)		NOT NULL,
	DESCRICAO					VARCHAR(500)	NULL,
	CONSTRAINT PK_CARGO_SETOR_CONTATOS_FORNECEDOR PRIMARY KEY (ID_CONTATOS_FORNECEDOR),
	CONSTRAINT FK_CARGO_SETOR_CONTATOS_FORNECEDOR_CONTATOS_FORNECEDOR FOREIGN KEY (ID_CONTATOS_FORNECEDOR)
	REFERENCES CONTATOS_FORNECEDOR (ID)
);

CREATE TABLE FILIAL_FORNECEDOR

(
	ID				INT				NOT NULL IDENTITY(1,1),
	ID_FORNECEDOR	INT				NOT NULL,
	RAZAO_SOCIAL	VARCHAR(100)	NOT NULL,
	NOME_FANTASIA	VARCHAR(50)		NULL,
	CNPJ			VARCHAR(20)		NOT NULL,
	CONSTRAINT PK_FILIAL_FORNECEDOR PRIMARY KEY (ID),
	CONSTRAINT FK_FILIAL_FORNECEDOR_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR)
	REFERENCES FORNECEDOR (ID)
);

CREATE TABLE LOJA_FISICA

(
	ID		INT				NOT NULL IDENTITY(1,1),
	NOME	VARCHAR(50)		NOT NULL,
	CNPJ	VARCHAR(20)		NOT NULL,
	CONSTRAINT PK_LOJA_FISICA PRIMARY KEY (ID)
);

CREATE TABLE ENDERECO_LOJA_FISICA

(
	ID_LOJA_FISICA		INT				NOT NULL,
	TIPO_LOGRADOURO		VARCHAR(20)		NOT NULL,
	NOME_LOGRADOURO		VARCHAR(50)		NOT NULL,
	NUMERO				VARCHAR(6)		NULL,
	COMPLEMENTO			VARCHAR(20)		NULL,
	BAIRRO				VARCHAR(50)		NOT NULL,
	CIDADE				VARCHAR(50)		NOT NULL,
	CEP					VARCHAR(8)		NULL,
	UF					VARCHAR(3)		NOT NULL,
	PAIS				VARCHAR(20)		NOT NULL,
	CONSTRAINT PK_ENDERECO_LOJA_FISICA PRIMARY KEY (ID_LOJA_FISICA),
	CONSTRAINT FK_ENDERECO_LOJA_FISICA_LOJA_FISICA FOREIGN KEY (ID_LOJA_FISICA)
	REFERENCES LOJA_FISICA (ID)
);

CREATE TABLE TIPO_TELEFONE_LOJA_FISICA

(
	ID					INT				NOT NULL IDENTITY(1,1),
	NOME				VARCHAR(50)		NOT NULL,
	DESCRICAO			VARCHAR(500)	NULL,
	CONSTRAINT PK_TIPO_TELEFONE_LOJA_FISICA PRIMARY KEY (ID)
);

CREATE TABLE TELEFONE_LOJA_FISICA

(
	ID								INT				NOT NULL IDENTITY(1,1),
	ID_LOJA_FISICA					INT				NOT NULL,
	ID_TIPO_TELEFONE_LOJA_FISICA	INT				NOT NULL,
	DDD								VARCHAR(3)		NOT NULL,
	N_TELEFONE						VARCHAR(9)		NOT NULL,
	CONSTRAINT PK_TELEFONE_LOJA_FISICA PRIMARY KEY (ID),
	CONSTRAINT FK_TELEFONE_LOJA_FISICA_LOJA_FISICA FOREIGN KEY (ID_LOJA_FISICA)
	REFERENCES LOJA_FISICA (ID),
	CONSTRAINT FK_TELEFONE_LOJA_FISICA_TIPO_TELEFONE_LOJA_FISICA FOREIGN KEY (ID_TIPO_TELEFONE_LOJA_FISICA)
	REFERENCES TIPO_TELEFONE_LOJA_FISICA (ID)
);

CREATE TABLE PRODUTO

(
	ID					INT				NOT NULL IDENTITY(1,1),
	NOME				VARCHAR(50)		NOT NULL,
	QUANTIDADE			DECIMAL(10,2)	NOT NULL,
	VALOR				DECIMAL(10,2)	NOT NULL,
	DESCRICAO			VARCHAR(500)	NULL,
	UNIDADE				DECIMAL(10,2)	NOT NULL,
	CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)
);

CREATE TABLE VARIACAO_PRODUTO

(
	ID					INT				NOT NULL IDENTITY(1,1),
	ID_PRODUTO			INT				NOT NULL,
	NOME				VARCHAR(50)		NOT NULL,
	DESCRICAO			VARCHAR(500)	NULL,
	VALOR				DECIMAL(10,2)	NOT NULL,
	QUANT_VARIACAO		DECIMAL(10,2)	NOT NULL,
	CONSTRAINT PK_VARIACAO_PRODUTO PRIMARY KEY (ID),
	CONSTRAINT FK_VARIACAO_PRODUTO_PRODUTO FOREIGN KEY (ID_PRODUTO)
	REFERENCES PRODUTO (ID)
);

CREATE TABLE CONTROLE_ESTOQUE_PRODUTO

(
	ID					INT				NOT NULL IDENTITY(1,1),
	ID_PRODUTO			INT				NOT NULL,
	ID_USUARIO			INT				NOT NULL,
	ACAO				VARCHAR(10)		NOT NULL,
	QUANTIDADE			DECIMAL(10,2)	NOT NULL,
	DESCRICAO			VARCHAR(500)	NULL,
	DATA				DATE			NULL,
	CONSTRAINT PK_CONTROLE_ESTOQUE_PRODUTO PRIMARY KEY (ID),
	CONSTRAINT FK_CONTROLE_ESTOQUE_PRODUTO_PRODUTO FOREIGN KEY(ID_PRODUTO)
	REFERENCES PRODUTO(ID),
	CONSTRAINT FK_CONTROLE_ESTOQUE_ACESSO FOREIGN KEY (ID_USUARIO)
	REFERENCES ACESSO(ID)
);

CREATE TABLE CUPOM_FISCAL

(
	ID					INT				NOT NULL IDENTITY(1,1),
	ID_CLIENTE			INT				NOT NULL,
	DATA				DATETIME		NOT NULL,
	CONSTRAINT PK_CUPOM_FISCAL PRIMARY KEY (ID),
	CONSTRAINT FK_CUPOM_FISCAL_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(ID)
);

CREATE TABLE CUPOM_FISCAL_ITENS

(
	ID							INT				NOT NULL IDENTITY(1,1),
	ID_ACESSO_USUARIO			INT				NOT NULL,
	ID_CUPOM_FISCAL				INT				NOT NULL,
	ID_PRODUTO					INT				NOT NULL,
	VALOR						DECIMAL(10,2)	NOT NULL,
	QUANTIDADE					DECIMAL(10,2)	NOT NULL,
	CONSTRAINT PK_CUPOM_FISCAL_ITENS PRIMARY KEY (ID),
	CONSTRAINT FK_CUPOM_FISCAL_ITENS_ACESSO_USUARIO FOREIGN KEY(ID_ACESSO_USUARIO)
	REFERENCES ACESSO(ID),
	CONSTRAINT FK_CUPOM_FISCAL_ITENS_CUPOM_FISCAL FOREIGN KEY (ID_CUPOM_FISCAL)
	REFERENCES CUPOM_FISCAL (ID),
	CONSTRAINT FK_CUPOM_FISCAL_ITENS_PRODUTO FOREIGN KEY (ID_PRODUTO)
	REFERENCES PRODUTO (ID)
);

CREATE TABLE ATUALIZACAO_ESTOQUE

(
	ID							INT				NOT NULL IDENTITY(1,1),
	ID_CUPOM_FISCAL_ITENS		INT				NOT NULL,
	ID_CONTROLE_ESTOQUE_PRODUTO	INT				NOT NULL,
	QUANTIDADE_VENDIDOS			DECIMAL(10,2)	NOT NULL,
	ACAO						VARCHAR(50)		NOT NULL,
	DESCRICAO					VARCHAR(500)	NULL,
	CONSTRAINT PK_ATUALIZACAO_ESTOQUE PRIMARY KEY (ID),
	CONSTRAINT FK_ATUALIZACAO_ESTOQUE_CUPOM_FISCAL_ITENS FOREIGN KEY (ID_CUPOM_FISCAL_ITENS)
	REFERENCES CUPOM_FISCAL_ITENS(ID),
	CONSTRAINT FK_ATUALIZACAO_ESTOQUE_CONTROLE_ESTOQUE_PRODUTO FOREIGN KEY(ID_CONTROLE_ESTOQUE_PRODUTO)
	REFERENCES CONTROLE_ESTOQUE_PRODUTO(ID)
);

CREATE TABLE TELAS

(
	ID				INT		NOT NULL IDENTITY(1,1),
	ID_CLIENTE		INT		NOT NULL,
	ID_FORNECEDOR	INT		NOT NULL,
	ID_LOJA_FISICA	INT		NOT NULL,
	ID_PRODUTO		INT		NOT NULL,
	ID_VENDAS		INT		NOT	NULL,
	CONSTRAINT PK_TELAS PRIMARY KEY (ID),
	CONSTRAINT FK_TELAS_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(ID),
	CONSTRAINT FK_TELAS_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR)
	REFERENCES FORNECEDOR(ID),
	CONSTRAINT FK_TELAS_LOJA_FISICA FOREIGN KEY (ID_LOJA_FISICA)
	REFERENCES LOJA_FISICA(ID),
	CONSTRAINT FK_TELAS_PRODUTO FOREIGN KEY (ID_PRODUTO)
	REFERENCES PRODUTO(ID),
	CONSTRAINT FK_TELAS_VENDAS FOREIGN KEY (ID_VENDAS)
	REFERENCES CUPOM_FISCAL_ITENS(ID)
);

CREATE TABLE PERMISSAO_ACESSO

(
	ID					INT				NOT NULL IDENTITY(1,1),
	ID_PERFIL			INT				NOT NULL,
	ID_TELAS			INT				NOT NULL,
	NOME_ROTINA			VARCHAR(50)		NOT NULL,
	DESCRICAO_ROTINA	VARCHAR(500)	NULL,
	ENDERECO_ACESSO		VARCHAR(500)	NOT NULL,
	CONSTRAINT PK_PERMISSAO_ACESSO PRIMARY KEY (ID),
	CONSTRAINT FK_PERMISSAO_ACESSO_PERFIL FOREIGN KEY (ID_PERFIL)
	REFERENCES PERFIL(ID),
	CONSTRAINT FK_PERMISSAO_ACESSO_TELAS FOREIGN KEY (ID_TELAS)
	REFERENCES TELAS(ID)
);